from sqlalchemy.orm import Session
from sqlalchemy import select
import models
import auth

def get_user_by_email(db: Session, email: str):
    """
    Fetches a user by their email address. Returns None if not found.
    """
    stmt = select(models.User).where(models.User.email==email)
    return db.scalars(stmt).first()

def create_user(db: Session, username: str, email: str, password: str):
    """
    Hashes the password and saves a new user to the database.
    """
    # 1. Hash the plain text password
    hashed_pw = auth.get_password_hash(password)

    # 2. Create the Python object
    db_user = models.User(
        username = username,
        email = email,
        password_hash = hashed_pw
    )

    # 3. Stage the object to be saved
    db.add(db_user)

    # 4. Commit the transaction to write it to PostgreSQL
    db.commit()

    # 5. Refresh the object so it gets the new UUID generated by the database
    db.refresh(db_user)

    return db_user

def create_custom_problem(
    db: Session,
    user_id: str, # This comes from the JWT, not the user input
    title: str, 
    difficulty: str, 
    url: str, 
    topic: str,
    source: str = "Manual Entry",
    notes: str | None = None
):
    """
    Saves a new custom problem and links it to the authenticated user.
    """
    db_problem = models.CustomProblem(
        user_id=user_id,
        title=title,
        difficulty=difficulty,
        url=url,
        topic=topic,
        source=source,
        notes=notes
    )

    db.add(db_problem)
    db.commit()
    db.refresh(db_problem)
    return db_problem

def get_user_custom_problems(db: Session, user_id: str, skip: int = 0, limit: int = 100):
    """
    Fetches a paginated list of custom problems for a specific user.
    """
    stmt = select(models.CustomProblem).where(models.CustomProblem.user_id == user_id).offset(skip).limit(limit)
    return db.scalars(stmt).all()

def update_custom_problem_notes(db: Session, problem_id: int, user_id: str, new_notes: str):
    """
    Updates the notes of a specific problem. 
    Crucially checks user_id to ensure the user actually owns the problem.
    """
    stmt = select(models.CustomProblem).where(
        models.CustomProblem.id == problem_id,
        models.CustomProblem.user_id == user_id # Security check!
    )

    db_problem = db.scalars(stmt).first()

    if not db_problem:
        return None
    
    # Modify the Python object directly
    db_problem.notes = new_notes

    # Commit the changes to the database
    db.commit()
    db.refresh(db_problem)
    return db_problem

def delete_custom_problem(db: Session, problem_id: int, user_id: str):
    stmt = select(models.CustomProblem).where(
        models.CustomProblem.id == problem_id,
        models.CustomProblem.user_id == user_id
    )
    db_problem = db.scalars(stmt).first()
    
    if db_problem:
        db.delete(db_problem)
        db.commit()
        return True
    return False

def create_user_solution(db: Session, user_id: str, problem_id: int):
    """
    Logs that a user solved a specific global problem.
    """
    db_solution = models.UserSolution(
        user_id=user_id,
        problem_id=problem_id
    )

    db.add(db_solution)
    db.commit()
    db.refresh(db_solution)
    return db_solution

def get_user_solutions(db: Session, user_id: str):
    """
    Fetches all standard problems a user has solved.
    """
    stmt = select(models.UserSolution).where(models.UserSolution.user_id == user_id)
    return db.scalars(stmt).all()

def get_problems_by_sheet(db: Session, sheet_name: str):
    """
    Fetches all global problems belonging to a specific sheet (e.g., 'NeetCode150').
    """
    stmt = select(models.Problem).where(models.Problem.sheet_name == sheet_name)
    return db.scalars(stmt).all()

def get_all_sheet_names(db: Session):
    """
    Returns a distinct list of all available sheets so the frontend can build a dropdown menu.
    """
    stmt = select(models.Problem.sheet_name).distinct()
    return db.scalars(stmt).all()