"""Add topic column to Problem table

Revision ID: 1beb314d5748
Revises: c98139774f81
Create Date: 2026-05-10 09:21:32.482596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1beb314d5748'
down_revision: Union[str, Sequence[str], None] = 'c98139774f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('topic', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'topic')
    # ### end Alembic commands ###
