"""Add leetcode_username to users

Revision ID: cf16e5cfff7a
Revises: 1beb314d5748
Create Date: 2026-05-10 16:46:36.612537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf16e5cfff7a'
down_revision: Union[str, Sequence[str], None] = '1beb314d5748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('leetcode_username', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'users', ['leetcode_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'leetcode_username')
    # ### end Alembic commands ###
